version: '3'

services:

  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - db
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: db
      database__connection__password: password
    networks:
      - my-network

  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network
volumes:
  db-data:

networks:
  my-network: